version: "3"

services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command: "ganache-cli -d -m -i 100 -l 20000000"

  facebox:
    restart: unless-stopped
    image: machinebox/facebox:latest
    ports:
      - 8080:8080
    environment:
      - MB_KEY=NzFjZGJmNzUzYmNlYjMwOWFkYTNiNjhiMWFmNjBjOTQ.Lu0oQeEWNmTewONjlTHnrwyLkBA5E7BqH_bljeX--GbYdDuXFO0mLO9EzGWqJ0KzIltpeU9PnqxjzGwU2ii5QQ

  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 4200:4200
    depends_on:
      - facebox
  # client-api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./src/client/assets:/assets
  #   depends_on:
  #     - server
